apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: twitter
  name: twitter
spec:
  containers:
  - args:
    - python
    - Tweets.py
    image: emmetk3094/twitter_streamer
    name: twitter
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
